apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: microservice-db-data
  name: microservice-db-data
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
