apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: temporal-pgdata
  name: temporal-pgdata
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
